switch to asm as a workaround for unsolved error in wasm
Uncaught (in promise) TypeError: Z.Fa is not a function
    x https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:168
    onRuntimeInitialized https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:75
    a https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:169
    cd https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:170
    bd https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:168
    a https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:161
    initSqlJsPromise https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:162
    promise callback*initSqlJs/initSqlJsPromise</db/< https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:100
    promise callback*db https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:100
    Z https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:162
    initSqlJsPromise https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:162
    initSqlJs https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.10.3/sql-wasm.js:22